giantswarm/apiextensions

pkg/apis/cluster/v1alpha1/kvm_types.go
=> add-vni-to-kvmtpr

pkg/apis/cluster/v1alpha1/common_types.go
=> added missing cloud provider property

pkg/apis/provider/v1alpha1/aws_types.go, pkg/apis/provider/v1alpha1/azure_types.go, pkg/apis/provider/v1alpha1/doc.go, pkg/apis/provider/v1alpha1/kvm_types.go, pkg/apis/provider/v1alpha1/register.go
Code generation comes in next PR.
=> aligned provider in code

pkg/apis/provider/v1alpha1/azure_types.go
Requires https://github.com/giantswarm/apiextensions/pull/27 to be merged
=> privider: add yaml tags for azure

pkg/apis/core/v1alpha1/cert_types.go
Towards https://github.com/giantswarm/giantswarm/issues/2449.
=> added flag to CertConfig to configure regeneration

pkg/apis/core/v1alpha1/chart_types.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
Towards giantswarm/giantswarm#1902
Fixes a copy paste fail in my previous PR.
=> Fix chartconfig spec

helm/apiextensions-kvm-config-e2e-chart/templates/cluster.yaml
=> add-networksetup-image

pkg/apis/core/v1alpha1/flannel_types.go
Reverts giantswarm/apiextensions#224
I misunderstood flannel configuration
=> Revert "Add basedomain into flannelconfig"

README.md
See https://gigantic.slack.com/archives/C04TGHDEF/p1576509099003600?thread_ts=1576509099.003600
=> Added note about GO111MODULE=off in README

pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go, pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
Attempts to fix the errors discovered in https://github.com/giantswarm/cluster-operator/pull/928.
=> fix Control Plane schema errors

docs/cr/application.giantswarm.io_v1alpha1_app.yaml, docs/crd/application.giantswarm.io_app.yaml, pkg/apis/application/v1alpha1/app_types.go, pkg/apis/application/v1alpha1/app_types_test.go
- Adds description to schema
- Adds creation of CRD and CR YAML files to unit tests
=> Enhance App CRD for documentation

docs/crd/infrastructure.giantswarm.io_awscluster.yaml, pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go
=> Set proper main comment in AWSCluster CRD

docs/cr/infrastructure.giantswarm.io_v1alpha2_awsmachinedeployment.yaml, docs/crd/infrastructure.giantswarm.io_awsmachinedeployment.yaml, pkg/apis/infrastructure/v1alpha2/aws_machine_deployment_types.go, pkg/apis/infrastructure/v1alpha2/aws_machine_deployment_types_test.go
=> Enhance AWSMachineDeployment for documentation

README.md
Towards https://github.com/giantswarm/giantswarm/issues/8436
I have protected this new branch already so it just needs a little documentation on `master`.
=> Document branches in readme

CHANGELOG.md, docs/pull_request_template.md
=> add missing changelogs

docs/crd/cluster.x-k8s.io_machinedeployment.yaml, pkg/apis/infrastructure/v1alpha2/cluster_api_crds_test.go
Fixing an error I introduced in https://github.com/giantswarm/apiextensions/pull/403
=> Fix bad YAML for MachineDeployment

CHANGELOG.md
=> Add missing releases to changelog

CHANGELOG.md
=> release v0.3.0

CHANGELOG.md
=> changelog: small improvements

CHANGELOG.md, pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go, pkg/apis/infrastructure/v1alpha2/common_cluster_status_types.go
=> make more status fields omitempty

CHANGELOG.md
=> release v0.3.1

CHANGELOG.md
Update release date for v0.3.2 when doing the release now.
=> Release v0.3.2 immediately

CHANGELOG.md, pkg/apis/core/v1alpha1/azure_cluster_types.go, pkg/apis/provider/v1alpha1/azure_types.go
=> Graduate Azure CRD's to v1

CHANGELOG.md
=> Release v0.3.4

CHANGELOG.md
=> Release v0.3.5

CHANGELOG.md
=> release 0.3.6

CHANGELOG.md
=> Release v0.3.7

CHANGELOG.md, pkg/apis/core/v1alpha1/drainer_types.go
=> CRD v1 for drainerconfigs

CHANGELOG.md
=> Prepare 0.3.9 version

CHANGELOG.md
=> Prepare 0.3.11

CHANGELOG.md
=> release v0.4.0

CHANGELOG.md
=> Release 0.4.3

CHANGELOG.md
=> Add v0.4.5 release to changelog

CHANGELOG.md
=> prepare release v0.4.6

CHANGELOG.md
=> Release v0.4.7

CHANGELOG.md
=> Release v0.4.9

.github/workflows/zz_generated.create_release.yaml, .github/workflows/zz_generated.create_release_pr.yaml
=> Add GitHub workflows

CHANGELOG.md
=> Update changelog for release reference changes

CHANGELOG.md, pkg/label/version.go
=> Add AzureOperatorVersion to pkg/label

CHANGELOG.md, pkg/apis/core/v1alpha1/storage_types.go
=> Graduate StorageConfig CRD

pkg/label/id.go, pkg/label/version.go
Towards https://github.com/giantswarm/giantswarm/issues/11748
=> Add managed-by label and version labels for app-operator and chart-operator

CHANGELOG.md
Add missing changelog entry for https://github.com/giantswarm/apiextensions/pull/551
=> Add missing changelog for labels changes

CHANGELOG.md, pkg/annotation/oidc.go
Towards https://github.com/giantswarm/giantswarm/issues/12093
=> Add annotations used for OIDC

CHANGELOG.md, docs/cr/infrastructure.giantswarm.io_v1alpha2_networkpool.yaml, pkg/apis/infrastructure/v1alpha2/network_pool_types_test.go, pkg/apis/infrastructure/v1alpha2/networkpool.go
=> Add networkpools functions to create CRs

CHANGELOG.md, config/crd/v1/security.giantswarm.io_organizations.yaml, config/crd/v1beta1/security.giantswarm.io_organizations.yaml, pkg/apis/security/v1alpha1/organization_types.go, pkg/crd/internal/zz_generated.fs.go
Towards https://github.com/giantswarm/giantswarm/issues/13619
=> Add organization CR description

CHANGELOG.md
=> Add 2.6.2 entry to changelog

pkg/annotation/aws.go, pkg/annotation/nodeautomation.go
=> add alpha prefix for new annotations

CHANGELOG.md, config/crd/v1/release.giantswarm.io_releases.yaml, config/crd/v1beta1/release.giantswarm.io_releases.yaml, pkg/apis/release/v1alpha1/release_types.go, pkg/crd/internal/zz_generated.fs.go
Towards https://github.com/giantswarm/giantswarm/issues/14239
=> Make release status fields optional

CHANGELOG.md, pkg/annotation/version.go, pkg/label/version.go
Towards https://github.com/giantswarm/giantswarm/issues/14603
=> Add config related annotation and label

CHANGELOG.md, pkg/annotation/version.go
=> change ConfigMajorVersion annotation

CHANGELOG.md
=> Fix header of CHANGELOG.md

CHANGELOG.md, go.mod, go.sum
=> Use latest CAPI fork

CHANGELOG.md, docs/cr/exp.infrastructure.cluster.x-k8s.io_v1alpha3_azuremachinepool.yaml, docs/cr/infrastructure.cluster.x-k8s.io_v1alpha3_azurecluster.yaml, docs/cr/infrastructure.cluster.x-k8s.io_v1alpha3_azuremachine.yaml
=> Add sample CRs for Azure Cluster API types.

CHANGELOG.md, pkg/annotation/aws.go
=> update aws-subnet-size annotation docs to explain the current behaviour

CHANGELOG.md, README.md, config/crd/provider.giantswarm.io_kvmconfigs.yaml, hack/build-charts.go, helm/crds-kvm/templates/giantswarm.yaml, pkg/apis/provider/v1alpha1/kvm_types.go
Closes https://github.com/giantswarm/giantswarm/issues/17340
=> Add validation for KVM node host volumes

CHANGELOG.md, config/crd/core.giantswarm.io_certconfigs.yaml, helm/crds-common/templates/giantswarm.yaml, pkg/apis/core/v1alpha1/cert_types.go
The CertConfig resource is not documented at all. Let's change that.
Please add your suggestions for improvements.
=> Add documentation to the CertConfig/v1alpha1 CRD

CHANGELOG.md, docs/config.yaml
Changes ownership of the Silence CRD to Atlas.
=> Assign silence to team Atlas

CHANGELOG.md, docs/config.yaml
Towards https://github.com/giantswarm/giantswarm/issues/18019
This PR adds docs metadata about CRD deprecation
=> Add CRD deprecation metadata

CHANGELOG.md, docs/config.yaml
=> Add kvm as a valid provider in docs metadata

CHANGELOG.md, docs/cr/monitoring.giantswarm.io_v1alpha1_silence.yaml, pkg/apis/monitoring/v1alpha1/silence_types.go, pkg/apis/monitoring/v1alpha1/silence_types_test.go
=> Add documentation for the silence.monitoring.giantswarm.io/v1alpha1 CRD.

CHANGELOG.md, pkg/annotation/azure.go, pkg/annotation/clusterautoscaler.go
Towards: https://github.com/giantswarm/giantswarm/issues/18086
This PR adds documentation about customer facing annotations we use in Azure.
=> Add documentation about azure annotations

CHANGELOG.md, pkg/apis/infrastructure/v1alpha2/network_pool_types.go
Fixes local and CI validation failures.
=> Add AWS category to network pool v1alpha2

CHANGELOG.md, docs/cr/application.giantswarm.io_v1alpha1_app.yaml, pkg/apis/application/v1alpha1/app_types_test.go
Towards https://github.com/giantswarm/giantswarm/issues/18349
=> Remove App CR version label as its always defaulted

CHANGELOG.md, pkg/annotation/aws.go, pkg/annotation/cluster.go
Towards https://github.com/giantswarm/giantswarm/issues/18077
I am using these annotations for now while working on the upgrade-schedule-operator. This won't be merged until other things are in order so open to other suggestions.
=> add upgrade annotations

CHANGELOG.md, hack/assets.go, hack/patches.go, helm/crds-vmware/templates/upstream.yaml
Towards https://github.com/giantswarm/roadmap/issues/456
=> Update CAPV CRDs to v1alpha4

pkg/annotation/cluster.go
=> enforce UTC for update schedule target time

docs/config.yaml
=> Handover ownership from batman to honeybadger

CHANGELOG.md, hack/assets.go, helm/crds-common/templates/release.giantswarm.io_releases.yaml
Signed-off-by: Marcus Noble <github@marcusnoble.co.uk>
=> Re-added preview release state

CHANGELOG.md, hack/assets.go, helm/crds-common/templates/backup.giantswarm.io_etcdbackups.yaml
=> Upgrade etcdbackup CRD

hack/assets.go, helm/crds-common/templates/application.giantswarm.io_appcatalogentries.yaml, helm/crds-common/templates/application.giantswarm.io_apps.yaml
=> Use latest apiextensions-application

CHANGELOG.md, pkg/annotation/aws.go
EBS Volume settings for AWSControlPlane CR for docs.giantswarm.io.
https://github.com/giantswarm/roadmap/issues/916
=> Document EBS volume settings annotations

CHANGELOG.md, go.mod, hack/assets.go, hack/build-charts.go, hack/patches.go, pkg/apis/core/v1alpha1/cert_types.go, pkg/apis/core/v1alpha1/kvm_cluster_types.go, pkg/apis/infrastructure/v1alpha3/aws_cluster_types.go, pkg/apis/infrastructure/v1alpha3/aws_control_plane_types.go, pkg/apis/infrastructure/v1alpha3/g8s_control_plane_types.go, pkg/apis/provider/v1alpha1/aws_types.go, pkg/apis/provider/v1alpha1/kvm_types.go
=> Bump go module major version to v6

CHANGELOG.md, hack/assets.go, helm/crds-common/templates/application.giantswarm.io_catalogs.yaml
Towards https://github.com/giantswarm/giantswarm/issues/21782
=> Update apiextensions-application to v0.4.0

docs/config.yaml
=> Add team hydra to relevant docs

CHANGELOG.md, hack/assets.go, helm/crds-common/templates/application.giantswarm.io_apps.yaml
=> Bump apiextensions-applications to v0.5.0 and run make generate

CHANGELOG.md, hack/assets.go, helm/crds-common/templates/application.giantswarm.io_apps.yaml
=> Bump apiextensions-application to v0.5.1

CHANGELOG.md, pkg/annotation/cilium.go
=> Add `cilium.giantswarm.io/pod-cidr` annotation.

.nancy-ignore, CHANGELOG.md, hack/assets.go, helm/crds-common/templates/application.giantswarm.io_apps.yaml, helm/crds-common/templates/application.giantswarm.io_charts.yaml
Towards: https://github.com/giantswarm/giantswarm/issues/23699
=> Timeout support in App and Chart CRs

CHANGELOG.md, docs/config.yaml
=> Update ownership for api-extensions
