giantswarm/apiextensions

- pkg/apis/provider/v1alpha1/common_types.go
Adds version to the cluster common type. This is for AWS to determine if clusters need the locked down config. I ran `scripts/gen.sh` but no changes were made.
> Add version to cluster common type

- pkg/apis/provider/v1alpha1/azure_types.go
In the operator it is reused from Cluster part of the object.
See: https://github.com/giantswarm/azure-operator/pull/97.
> provider/v1alpha1: remove Azure node SSH config

- pkg/apis/provider/v1alpha1/kvm_types.go
I want to get rid of certain settings in the custom objects. Here we deprecate the Docker image of the KVM node-controller. In the future we can then remove all related code as soon as no existing guest cluster makes use of this anymore. See also https://github.com/giantswarm/kubernetesd/pull/359 and https://github.com/giantswarm/kvm-operator/pull/366.
> added deprecation comments to KVMConfig

- pkg/apis/core/v1alpha1/chart_types.go
- pkg/clientset/versioned/fake/clientset_generated.go
Towards giantswarm/giantswarm#1902
Adds the release name as its needed in the chart resource to get the current state.
> Add release name to chartconfig

- pkg/apis/core/v1alpha1/cluster_guest_types.go
As suggested in previous [PR](https://github.com/giantswarm/apiextensions/pull/59), DNSZone communicates purpose of this field
better than CommonDomain.
> Improve naming: CommonDomain -> DNSZone

- pkg/apis/provider/v1alpha1/azure_types.go
Towards https://github.com/giantswarm/azure-operator/issues/115
Provide host cluster virtual network's name in AzureConfig
> Add azure host cluster network name

- pkg/apis/application/v1alpha1/app_types.go
I noticed that we're not using `AppSpecUserConfig` where I think it should be used.
Alternatively, we could remove `AppSpecUserConfig`, if we think that `App.Spec.Config` and `App.Spec.UserConfig` will be the same type of thing always.
ping @rossf7 
Release operator has implemented it with `UserConfig` as `AppSpecConfig` instead of `AppSpecUserConfig`, so we'd have to make a change there too:
https://github.com/search?q=org%3Agiantswarm+AppSpecConfig&type=Code
ping @rossf7
> Actually use AppSpecUserConfig

- Gopkg.toml
Reverts giantswarm/apiextensions#266
Pretty sure that dep's semver `~` operator won't work without a fully `vX.Y.Z` release verison
> Revert "Support Kubernetes packages minor range constraint"

- pkg/apis/provider/v1alpha1/azure_types.go
After live discussion, we decided to undo https://github.com/giantswarm/apiextensions/pull/293 and make the Kubelet Volume size adjustable.
That's to allow us to resize the tenant cluster storage size more easily.
Related issue: https://github.com/giantswarm/giantswarm/issues/7526
> Removed RootVolumeSizeGB, Added KubeletVolumeSizeGB for azureConfig

- pkg/apis/core/v1alpha1/ignition_types.go
For https://github.com/giantswarm/giantswarm/issues/8646
From what I understand, we want to remove images from the ignition CR because it will be looked up dynamically based on TC release. If so, this PR removes etcd and k8s images but leaves the docker network setup env image since that's separate.
> Remove image from components sources from releases

- pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go
- pkg/apis/infrastructure/v1alpha2/common_cluster_status_types.go
This PR is exploring how adding per-field comments improves the usability of Godoc documentation at https://pkg.go.dev/github.com/giantswarm/apiextensions/pkg/apis/infrastructure/v1alpha2?tab=doc#AWSCluster
> Provide descriptive comments for the AWSCluster CR/type

- pkg/apis/application/v1alpha1/app_types.go
This sets the code block indentation for the App type from 3 to 4 blanks, in order to check whether this influences the code block rendering with some documentation generation tool.
It also fixes the indentation in line 174.
> Modify code block indentation for App

- pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
Learning made in https://github.com/giantswarm/aws-operator/pull/2162 the owner reference is actually a list and does not hold a namespace because you cannot define owners outside of the object's namespace by system design.
> fix owner reference in godoc example for AWSControlPlane CR

- docs/cr/core.giantswarm.io_v1alpha1_ignition.yaml
- docs/cr/release.giantswarm.io_v1alpha1_release.yaml
- docs/crd/core.giantswarm.io_ignition.yaml
- docs/crd/release.giantswarm.io_release.yaml
- pkg/apis/core/v1alpha1/ignition_types.go
- pkg/apis/core/v1alpha1/ignition_types_test.go
- pkg/apis/release/v1alpha1/release_types_test.go
Since we don't want a status section in our documentation CRDs/CRs, I created this PR to delete `status` after marshaling using a simple regex. This PR includes a few other small fixes to release and ignition CRs.
Other changes:
- remove status
- update docs annotation
- remove directory creation
- use full ignition example
> Remove status and improve docs and examples

- docs/cr/release.giantswarm.io_v1alpha1_release.yaml
- docs/crd/release.giantswarm.io_release.yaml
- pkg/apis/release/v1alpha1/deep_copy.go
- pkg/apis/release/v1alpha1/release_types.go
- pkg/apis/release/v1alpha1/release_types_test.go
Towards https://github.com/giantswarm/releases/pull/142
We can't set `creationTimestamp` to reflect the release date so we need a separate date in the `spec`. I added this field with tests and improved the example `Release` for our docs since it wasn't showing much before.
I also took this opportunity to remove `version` after a [team discussion](https://gigantic.slack.com/archives/CHAHY6VMF/p1582851678004100?thread_ts=1582851678.004100&cid=CHAHY6VMF). There are good reasons to keep it and good reasons to get rid of it. In general, Kubernetes resource names should not have meaning. The name is metadata and the important information should be in the spec and status. At the same time, we are able to validate names with OpenAPI and stateful sets do use meaningful pod names. Moreover, getting …
> Various release changes

- docs/crd/infrastructure.giantswarm.io_awscluster.yaml
- pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go
As pointed out by @paurosello in https://github.com/giantswarm/giantswarm/issues/8804#issuecomment-597517421 the schema for AWSCluster wasn't represented correctly. The reason was bad indentation in the CRD YAML.
This PR fixes that.
The example PR in our docs shows the correct hierarchy:
> Fix indentation in the AWSCluster CRD YAML

- docs/cr/core.giantswarm.io_v1alpha1_ignition.yaml
- helm/apiextensions-aws-cluster-config-e2e-chart/values.yaml
- pkg/apis/core/v1alpha1/ignition_types_test.go
For the validation of hyperlinks in our documentation, it would be nice to limit the amount of domains used (and which we can configure an exclusion rule in the link checker for). As I don't want to make an exclusion for `giantswarm.io`, but instead for `gigantic.io`, I am voting for using that domain in the examples, which is the one we actually use in clusters.
To fully explain the problem:
When building docs, the link checker tries to verify URLs like `https://etcd.abc12.k8s.example.eu-west-1.aws.giantswarm.io` and fails. [Example](https://circleci.com/gh/giantswarm/docs/1210?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
> Change example URLs to use gigantic.io domain

- pkg/apis/backup/v1alpha1/etcd_backup_types.go
Added new fields to the status spec for the etcd-backup type.
Those fields hold some metric information about the backup process that the operator will return to prometheus.
> Added metrics to the etcd backup CR

- docs/crd/provider.giantswarm.io_awsconfig.yaml
- pkg/apis/provider/v1alpha1/aws_types.go
Based on and to be merged into https://github.com/giantswarm/apiextensions/pull/372
This adds the OpenAPIv3 validation schema for the AWSConfig CRD.
> Add AWSConfig validation schema

- docs/cr/infrastructure.giantswarm.io_v1alpha2_awscontrolplane.yaml
- pkg/apis/infrastructure/v1alpha2/aws_control_plane_types_test.go
I figured that the example I crafted would be invalid according to our own description.
> Add third AZ to AWSControlPlane example

- docs/cr/infrastructure.giantswarm.io_v1alpha2_machinedeployment.yaml
- docs/crd/infrastructure.giantswarm.io_machinedeployment.yaml
- pkg/apis/infrastructure/v1alpha2/cluster_api_crds.go
- pkg/apis/infrastructure/v1alpha2/cluster_api_crds_test.go
Based on https://github.com/giantswarm/apiextensions/pull/375 and to be merged into `cluster-docs`.
Changes
1. Makes CRD initialized from YAML string
2. Create CR and CRD files in docs folder via unit tests
As in https://github.com/giantswarm/apiextensions/pull/375 there is an open question regarding the file name schema in the docs folder.
> Document MachineDeployment CRD

- .circleci/config.yml
- pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go
Just a little cosmetic. It looks like this in a lot of places. 
```
oidc:
claims:
groups: ""
username: ""
clientID: ""
issuerURL: ""
```
With this PR it is like this. 
```
oidc:
claims: {}
```
> make oidc fields omitempty

- CHANGELOG.md
- pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go
Towards https://github.com/giantswarm/giantswarm/issues/9274.
> add VPC ID to AWSCluster CR

- docs/cr/core.giantswarm.io_v1alpha1_certconfig.yaml
- docs/crd/core.giantswarm.io_certconfig.yaml
- pkg/apis/core/v1alpha1/cert_types.go
- pkg/apis/core/v1alpha1/cert_types_test.go
This prepares the CertConfig CRD to add OpenAPIv3 schema and property descriptions. It also provides an example CR which can be displayed in the CRD docs.
The example details are taken from a real world CR in an Azure installation.
> Prepare CertConfig for schema documentation

- CHANGELOG.md
- pkg/apis/application/v1alpha1/chart_types.go
Towards https://github.com/giantswarm/giantswarm/issues/9900
We've had problems with the chart CR status not being set correctly. This makes trouble shooting difficult and can cause alerts.
This adds the Helm revision number to the status. This is useful info and will ensure we always update the status when it changes.
> Add revision to chart CR status

- docs/cr/infrastructure.giantswarm.io_v1alpha2_g8scontrolplane.yaml
- docs/crd/infrastructure.giantswarm.io_g8scontrolplane.yaml
- pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
- pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types_test.go
- Adds YAML CRD and CR files generated by unit tests
- Adds property descriptions to the schema
> Document G8sControlPlane CRD

- CHANGELOG.md
- pkg/apis/core/v1alpha1/storage_types.go
I noticed in https://github.com/giantswarm/apiextensions/pull/441 that I didn't load the StorageConfig CRD from the pkger filesystem YAMLs. To keep the other PR small, I'm fixing this here.
> Fix StorageConfig CRD loading

- CHANGELOG.md
There was an accidental move of the `0.3.7` tag in `apiextensions`. This move of the tag completely breaks go modules. Therefore this empty release is necessary.
> Add changelog for empty 0.3.8 release

- CHANGELOG.md
- pkg/apis/application/v1alpha1/app_catalog_types.go
- pkg/apis/application/v1alpha1/app_types.go
- pkg/apis/application/v1alpha1/chart_types.go
- pkg/apis/backup/v1alpha1/etcd_backup_types.go
- pkg/apis/core/v1alpha1/aws_cluster_types.go
- pkg/apis/core/v1alpha1/azure_cluster_types.go
- pkg/apis/core/v1alpha1/cert_types.go
- pkg/apis/core/v1alpha1/chart_types.go
- pkg/apis/core/v1alpha1/drainer_types.go
- pkg/apis/core/v1alpha1/flannel_types.go
- pkg/apis/core/v1alpha1/ignition_types.go
- pkg/apis/core/v1alpha1/kvm_cluster_types.go
- pkg/apis/core/v1alpha1/storage_types.go
- pkg/apis/example/v1alpha1/memcached_types.go
- pkg/apis/infrastructure/v1alpha2/aws_cluster_types.go
- pkg/apis/infrastructure/v1alpha2/aws_control_plane_types.go
- pkg/apis/infrastructure/v1alpha2/aws_machine_deployment_types.go
- pkg/apis/infrastructure/v1alpha2/g8s_control_plane_types.go
- pkg/apis/provider/v1alpha1/aws_types.go
- pkg/apis/provider/v1alpha1/azure_types.go
- pkg/apis/provider/v1alpha1/kvm_types.go
- pkg/apis/release/v1alpha1/release_cycle_types.go
- pkg/apis/release/v1alpha1/release_types.go
- pkg/apis/tooling/v1alpha1/azure_tool_types.go
// +kubebuilder:storageversion marks the given CRD version as the one that
should be used for storage (i.e. persisting in etcd). When there are no other
versions of given CRD, it doesn't generate anything. When new version is added,
one must decided case-by-case which version should be stored in etcd.
This is preparation to introduce `infrastructure/v1alpha3` for Azure
Cluster API types and Node Pools.
> Add generation of CRD storageversion if multiple versions are present

- CHANGELOG.md
- pkg/crd/crd.go
I just found out that errors were being missed (namely `cannot convert int64 to float64`) while converting `AWSMachineDeployment` CRD from `unstructured.Unstructured` to `CustomResourceDefinition`. This PR adds more error checking and unmarshals CRDs from the YAML string rather than attempting to convert from `Unstructured`.
> Catch and fix errors while parsing CRDs

- CHANGELOG.md
- pkg/annotation/nodepool.go
- pkg/label/id.go
- pkg/label/version.go
Towards https://github.com/giantswarm/roadmap/issues/160
- Moved label `MachinePool` from API repo to `pkg/label`.
- Added annotation `MachinePoolName` to `pkg/annotation`.
> Add azure nodepool labels and annotations

- CHANGELOG.md
- pkg/annotation/cluster.go
Towards https://github.com/giantswarm/giantswarm/issues/12363
This adds a cluster description annotation, which we'll use to specify an user friendly cluster description for Azure v5 clusters.
> Add cluster description annotation

- CHANGELOG.md
- pkg/annotation/clusterautoscaler.go
Towards https://github.com/giantswarm/giantswarm/issues/13200
This PR adds 2 constants that hold the names of annotations needed by cluster autoscaler.
> Added new constants for cluster autoscaling annotations

- CHANGELOG.md
- docs/cr/infrastructure.giantswarm.io_v1alpha2_awscluster_networkpool.yaml
- pkg/apis/infrastructure/v1alpha2/aws_cluster_types_test.go
- pkg/apis/infrastructure/v1alpha2/cluster.go
> Add networkpool support on AWS Clusters

- CHANGELOG.md
- go.mod
- go.sum
For some reason that we don't know about yet, projects depending on latest release don't compile anymore because they try to use `cluster-api` `v0.3.7` together with k8s 1.18 dependencies.
We don't know what it started to happen in the last release, since we already did that change in the prior releases.
To fix this issue, projects depending on this library need to explicitly add a `replace` directive to their `go.mod` files. According to [the docs](https://github.com/golang/go/wiki/Modules#gomod)
> exclude and replace directives only operate on the current (“main”) module. exclude and replace directives in modules other than the main module are ignored when building the main module. The replace and exclude statements, therefore, allow the main module complete control over its own build, …
> Prepare next major, add warning to changelog

- CHANGELOG.md
- pkg/label/kubernetes.go
Towards giantswarm/giantswarm#11656
Needed for https://github.com/giantswarm/app-admission-controller/pull/23.
We want to default the `app.kubernetes.io/name` label but some app CRs have the legacy `app` label. e.g. those managed by cluster-operator.
> Add legacy app label

- CHANGELOG.md
- config/crd/v1/infrastructure.giantswarm.io_awsmachinedeployments.yaml
- config/crd/v1beta1/infrastructure.giantswarm.io_awsmachinedeployments.yaml
- pkg/apis/infrastructure/v1alpha2/aws_machine_deployment_types.go
- pkg/crd/internal/zz_generated.fs.go
Towards: https://github.com/giantswarm/giantswarm/issues/14429
We want to make the nodepool AZs optional so they can be defaulted.
> make nodepool AZs optional

- CHANGELOG.md
- pkg/annotation/app.go
`LatestConfigMapVersion`, `LatestSecretVersion` is needed by two operators at the moment. 
It makes sense to move these to apiextensions.
> Add annotations for apps

- CHANGELOG.md
- pkg/apis/core/v1alpha1/drainer_funcs.go
It is invalid to create a `Condition` with a `nil` `LastHeartbeatTime`, so this adds one. I think this was just missed when the equivalent timestamp for `LastTransitionTime` was added.
> Set LastHeartbeatTime when creating Conditions for DrainerConfigs

- CHANGELOG.md
- pkg/apis/application/v1alpha1/register.go
We need to add new CRDs into the registry to use it from unittest. 
Otherwise, we get an error below. 
```
--- FAIL: Test_ValidateMetadataConstraints/case_1:_fixed_namespace_constraint (0.00s)
panic: no kind is registered for the type v1alpha1.AppCatalogEntry in scheme "pkg/runtime/scheme.go:101" [recovered]
panic: no kind is registered for the type v1alpha1.AppCatalogEntry in scheme "pkg/runtime/scheme.go:101"
```
> Add appCatalogEntry into registry

- CHANGELOG.md
- pkg/id/id.go
- pkg/id/id_test.go
Towards https://github.com/giantswarm/giantswarm/issues/16193
This PR makes generated IDs not be able to start with digits. It also simplifies the previous implementation.
`api` and `kubectl-gs` should be updated to use this new generator.
> Refactor ID generation to block ids starting with digits

- CHANGELOG.md
- pkg/annotation/organization.go
We want to migrate fully to Organization CR's as the source of truth for Organizations, while delaying the task of figuring out how to migrate related resources.
Unfortunately, some organisations have a name that is incompatible with Organization CR's validation for names. That means, in order not to lose data, we will store that name into an annotation. This will let our UI's operate as normal, and further the transition to the MAPI.
> Document original-organization-name annotation

- helm/apiextensions-app-e2e-chart/values.yaml
Updates the catalog domain to giantswarm.github.io instead of giantswarm.github.com. Towards giantswarm/giantswarm#15898
> Update catalog domain to github.io

- .nancy-ignore
- hack/build-charts.go
- helm/crds-aws/templates/upstream.yaml
This PR supports multiple Github asset files to include EKS bootstrap and controlplane components because it is not included in `infrastructure.yaml`.
CRDs which are added:
- eksconfigs.bootstrap.cluster.x-k8s.io
- eksconfigtemplates.bootstrap.cluster.x-k8s.io
- awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
Additionally I had to add EKS config and EKS controlplane webhook for CRD conversion because they are in new API groups.
> Add EKS to AWS upstream CRD collection

- hack/build-charts.go
- helm/crds-azure/templates/upstream.yaml
I realized the aad-pod-identity CRDs were lost in the [previous PR](https://github.com/giantswarm/apiextensions/pull/712) because they are still v1beta1 CRDs.
> Bring back aad-pod-identity CRDs

- CHANGELOG.md
- pkg/annotation/nodeautomation.go
towards https://github.com/giantswarm/giantswarm/issues/16843
remove `alpha` prefix for the feature
> remove-alpha-prefix-for-node-termination

- CHANGELOG.md
- go.mod
- go.sum
- hack/assets.go
- helm/crds-azure/templates/upstream.yaml
Discussion from last month https://gigantic.slack.com/archives/CNUDS3AMU/p1620741721378000
Aad-pod-identity CRDs in v1.7x are still using CRD v1beta1. 1.8.0 updates them to v1. These are our last v1beta1 CRDs so we can drop a lot of v1beta1 handling code after this change.
> Update add-pod-identity to 1.8.0 for CRD v1

- CHANGELOG.md
- docs/config.yaml
Towards https://github.com/giantswarm/giantswarm/issues/18019
This PR consolidates CRD-related metadata and config in the apiextensions repository, which brings it closer to the maintenance of CRDs, and reduces the number of repositories to touch when dealing with CRDs.
> Store docs metadata and config on CRDs in apiextensions

- CHANGELOG.md
- config/crd/infrastructure.giantswarm.io_networkpools.yaml
- helm/crds-aws/templates/giantswarm.yaml
- pkg/apis/infrastructure/v1alpha3/network_pool_types.go
`opsctl ensure crds -i giraffe --crds networkpools.infrastructure.giantswarm.io` does not consider networkpools: 
**Skipping giraffe. CRDs [networkpools.infrastructure.giantswarm.io] not found.** 
because it [fetches all CRDs from helm directory](https://github.com/giantswarm/app/blob/d06c220fb642e086969f35865feff051a21f6a75/pkg/crd/crd.go#L209). This is currently missing.
By adding the category "aws" we can ensure this will be also included in helm directory.
> add networkpool into helm

- CHANGELOG.md
- pkg/apis/infrastructure/v1alpha3/cluster.go
- pkg/apis/infrastructure/v1alpha3/nodepool.go
When creating `v1alpha3` CR's directly, we need to include `clusterName` because it is a required field for `Machinedeployment`. We also want to add the upstream cluster label on all upstream CR's. 
New label which will be added when creating `v1alpha3` CR's directly:
`cluster.x-k8s.io/cluster-name: my-cluster`
Mandatory fields:
https://github.com/kubernetes-sigs/cluster-api/blob/dfeb8d447bdcc0206b7669df20f0e2f99c15d47a/api/v1alpha2/machinedeployment_types.go#L48-L51
https://github.com/kubernetes-sigs/cluster-api/blob/39f47041a7897b378956a8f7b69fe5ed4d8ab017/api/v1alpha3/machine_types.go#L57-L60
> Add required field to MD's and add cluster label to all upstream CR's

- CHANGELOG.md
- config/crd/monitoring.giantswarm.io_silences.yaml
- helm/crds-common/templates/giantswarm.yaml
- pkg/apis/monitoring/v1alpha1/silence_types.go
We can actually keep the existing silence CRD by adding a new value set to true by default
> Add support for new silence matcher types

- CHANGELOG.md
- docs/cr/cluster.x-k8s.io_v1alpha3_cluster.yaml
- docs/cr/cluster.x-k8s.io_v1alpha3_machinepool.yaml
- docs/cr/exp.cluster.x-k8s.io_v1alpha3_machinepool.yaml
- docs/cr/infrastructure.cluster.x-k8s.io_v1alpha3_azuremachinepool.yaml
Towards https://github.com/giantswarm/giantswarm/issues/15025
I'm adding two `MachinePools` and two `AzureMachinePools` but they belong to two different api groups. The ones with `exp` in the name will be removed eventually, as they got removed upstream.
> Add example CRs

- docs/config.yaml
- certs go to cabbage (see https://gigantic.slack.com/archives/C01L7DCFVFD/p1633359188003900)
- ignitions are not anymore
- releases to honey badger (to be deprecated)
> handing over ownership from ludacris

- CHANGELOG.md
- config/crd/release.giantswarm.io_releases.yaml
- helm/crds-common/templates/giantswarm.yaml
- pkg/apis/release/v1alpha1/release_types.go
Related issue: https://github.com/giantswarm/roadmap/issues/559
Notice field for use to indicate anything in the release to be aware of. 
e.g.
```
This is a preview release only intended to be used for testing. No support is offered at the moment.
```
> Added Notice property to Release CRD

- CHANGELOG.md
- go.mod
- go.sum
Mitigation for https://nvd.nist.gov/vuln/detail/CVE-2021-3121
> Replace all protobuf versions with v1.3.2

- CODEOWNERS
Since CAPZ is now in phoenix and the entire repo is owned by phoenix, this custom file is no longer needed.
The "Align files" (Synchronize) workflow will add a generated one.
> Delete custom (invalid) CODEOWNERS
